CLS
INPUT "How many times do you want this to play"; d
FOR hakunmat = 1 TO d
CLS
PRINT "This is the "; hakunmat; "th time it has played."
SOUND 660, 8: REM Ha
SOUND 30000, 1: REM silence
SOUND 660, 8: REM ku
SOUND 588, 4: REM na
SOUND 660, 4: REM ma
SOUND 588, 4: REM ta
SOUND 512, 4: REM ta
SOUND 30000, 32: REM rest
SOUND 440, 4: REM what
SOUND 512, 4: REM a
SOUND 588, 8: REM won
SOUND 624, 4: REM der
SOUND 588, 4: REM ful
SOUND 512, 32: REM phrase
SOUND 30000, 8: REM rest
NEXT hakunmat






